### ISSUE TITLE
RecHierarchy : You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by Ivan-Malinovski** [santisq/Get-Hierarchy#2]
When trying to run the script with any input, I get the error in the screenshot. It seems to have something to do with the pscustomobjects, but I can't quite figure it out. I have tried with many different groups and syntaxes, but results are always exactly the same.

I do have PowerShell 5.1, as required, so that's not it.

![image](https://user-images.githubusercontent.com/16567163/192998222-238284fb-3b0b-424a-88a9-836c796ab312.png)

This script is otherwise **exactly** what I needed, so I was excited to find it.

Got any ideas?

**Comment by santysq** [comment]
@Ivan-Malinovski thanks for reaching out, I'll try to look into this later. This function is very old one and already had plans to improve it, make it loo

**Comment by Ivan-Malinovski** [comment]
I just briefly tested it, and it seems to work now - thank you so much!

**Comment by santisq** [comment]
Commit https://github.com/santisq/Get-Hierarchy/commit/5f40862c3175cd6ee99a2e35ae828d1fb2adb816 fixes this issue.
